### ISSUE TITLE
Setup docker compose for MongoDB

### ISSUE THREAD

**Issue by tarikeshaq** [ubclaunchpad/news-sentiment#13]
# What is it
Currently, our DB work isn't tested and doesn't use an actual DB connection. The goal here is to set up that connection using docket, preferably setting up a docker-compose.

## Example
Here's an example: https://dev.to/sonyarianto/how-to-spin-mongodb-server-with-docker-and-docker-compose-2lef
TLDR, the docker-compose file can look something like this:
```yml
version: '3'
services:
       mongodb:
           image: mongo:latest
           environment: # Note it might be better to point to a .env file for this
              - MONGO_INITDB_ROOT_USERNAME 
              - MONGO_INITDB_ROOT_PASSWORD
           ports:
              - 27017:27017
           volumes:
              -./db/data:/data/db

```

## Deliverables
A tested docker-compose file that runs a docker container with the mongo image, sets environment variables appropriately, sets the correct ports and attaches a volume.
