### ISSUE TITLE
Styling the non-first page

### ISSUE THREAD

**Issue by tarikeshaq** [ubclaunchpad/news-sentiment#61]
We would like to style the page people see so that it's easier to work with.

Lets start off with removing everything there and leaving off just 1 button that says something like "Show me the news!"

Lets keep the slider on there commented out, we'll add it back later!

## Details:
- You would need to first adjust the [`mainView`](https://github.com/ubclaunchpad/news-sentiment/blob/main/frontend/popup/popup.html#L10-L17), comment out the `slideContainer` and the `contentClick` button.
- You would then format the button to look nice! You can add styling to the [css](https://github.com/ubclaunchpad/news-sentiment/blob/main/frontend/popup/popup.css) file. Search online for a nice looking button styling and place it in there, targeting the button using it's class. Example:
```css

button#getArticles {
    display: inline-block;
    padding:0.35em 1.2em;
    border:0.1em solid black;
    margin:0 0.3em 0.3em 0;
    border-radius:0.5em;
    box-sizing: border-box;
    text-decoration:none;
    font-family:'Roboto',sans-serif;
    font-weight:300;
    color: black;
    text-align:center;
    transition: all 0.2s;
    background-color: transparent;
}

button#getArticles:hover {
    color: white;
    background-color: black;
}

@media all and (max-width:30em){
 button#getArticles{
  display:block;
  margin:0.4em auto;
 }
}
```
This is a random button styling I found on https://fdossena.com/?p=html5cool/buttons/i.frag, feel free to use this, or others!
- Finally center the button on the page, look around the internet on how to center something, use the same principles in the above css to apply that!
